# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
#version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build app image
          command: |
            docker build -t app .
      - run:
          name: start cutom db image
          environment:
          command: |
            docker run -d --name db --env-file $PWD/test/test.env -p 5432:5432 -v $PWD/test/fixture:/osm-data citykleta/db:latest
      - run:
          name: check connectiviy
          command: |
            sleep 5s && docker logs db
      - run:
          name: Test app
          command: |
            docker run app npm test
